# Generated by Django 4.1.2 on 2022-10-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='otp_live_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
